name = "lean-lr"
version = "0.1.0"
defaultTargets = ["lean-lr"]

[[lean_lib]]
name = "LeanLR"

[[lean_exe]]
name = "lean-lr"
root = "Main"

[[require]]
name = "iris"
git = "https://github.com/leanprover-community/iris-lean"
rev = "master"
subDir = "Iris"
