import LeanLR.TypeSystems.SystemF.Lang
import LeanLR.TypeSystems.SystemF.Notation
import LeanLR.TypeSystems.SystemF.Types
import LeanLR.TypeSystems.SystemF.Pure
import LeanLR.TypeSystems.SystemF.ParallelSubst
import LeanLR.TypeSystems.SystemF.TypeSafety
import LeanLR.TypeSystems.SystemF.BigStep
import LeanLR.TypeSystems.SystemF.ChurchEncodings
import LeanLR.TypeSystems.SystemF.LogRel
import LeanLR.TypeSystems.SystemF.FreeTheorems
import LeanLR.TypeSystems.SystemF.ExistentialInvariants
import LeanLR.TypeSystems.SystemF.BinaryLogRel
import LeanLR.TypeSystems.SystemF.ChurchEncodingsFaithful
import LeanLR.TypeSystems.SystemF.Tactics
import LeanLR.TypeSystems.SystemF.Exercises03
import LeanLR.TypeSystems.SystemF.Exercises04
